### PR TITLE
Change the way docker setup work

### PR DESCRIPTION
**Pull request by RemiDesgrange**
* bump the version of some dep to work with python 3.8
* use some standard to run entrypoint and rename entrypoint to convention.
* add a `CMD` in the dockerfile ("override-able" by the `docker-compose`). Generally speaking, we try be as declarative as possible in a `Dockerfile` and follow KISS.
* `GIT_BRANCH` arg seems not used.

In a normal setup, `collectstatic` should happened at build time (but migration should stay at startup time).

As you can see the setup is quite complex. It could be simpler if you have a config project (not config_sample) and everything in the `settings.py` is override-able by env var (https://12factor.net/fr/) [Django-environ](https://django-environ.readthedocs.io/en/latest/) could you do that, it could reduce the size of the shell script and the dramatically reduce the size of the `Dockerfile`. A practical example: [django-cookiecutter](https://github.com/pydanny/cookiecutter-django)

### CODE REVIEW

**Comment by bchartier** [comment]
I'm sorry for the delay...
Thank you very much the improvements and the advises!

Some questions/comments:
- I think we could avoid the first copy statement in the following snippet (coming from your modified Dockerfile) since the requirements.txt file is located in src. We could juste remove the first copy and move the pip install command after the copy statement. Is this ok for you as well or is there any trouble with the ownership of the file while we would run the pip install command?
```
COPY requirements.txt .
RUN pip install --user -r requirements.txt gunicorn
COPY --chown=apprunner . src/
```

- you commented out the command line in the docker-compose file. This line is no more needed (if I understand well). Why not removing it?

- Collecstatic
> In a normal setup, collectstatic should happened at build time (but migration should stay at startup time).

So did you changed anything related to this in this PR?

- Python 3.8
> bump the version of some dep to work with python 3.8

I cannot see any modification in the source code of geocontrib for the use of the psycopg2 and pillow. Was it really necessary to upgrade the versions in the requirements.txt and switch to Python 3.8 in the docker-file? Upgrading these library is probably a good idea but we need to check that the app is not broken by these upgrades (since we the app is already deployed and used). But, in my opinion, this is not the right time to do this. First, we need to make the app run nicely in a dockerised geOrchestra environment. Could you revert the python version to 3.7 and the library versions?

- Settings et env: we will have a look at Django-environ et cookitcutter. Thanks a lot.

**Comment by RemiDesgrange** [comment]
I'm off this week. It's OK !!

* The first copy statement is here for caching. If you modify the code, but not the dependency, then the `pip install -r requirements.txt` will not be played. That's here for DX proprosed only :-)
* changing stuff to make the collectstatic at build time would require a working `settings.py`. If we do so, then the PR will be much more huge.
* you're right. I'll try to make it work with py3.7. But pillow6 does not work with py3.8 (did not investigate, not breaking change expected in 3.8 except C api, must be this.).

**Comment by bchartier** [comment]
I've merged your work with some adjustments in a new branch (see https://github.com/neogeo-technologies/geocontrib/commits/georchestra).

**Comment by RemiDesgrange** [comment]
(closing then ?)

Just one note, you are using OSM tiles from community server, that is not recommended for production use, it's not a "definitive" `settings.py` file so it's ok but maybe worth a little change.

**Comment by bchartier** [comment]
> (closing then ?)

We can wait before closing this PR. Just in case you have other comment about my integration of your work.

> Just one note, you are using OSM tiles from community server, that is not recommended for production use, it's not a "definitive" `settings.py` file so it's ok but maybe worth a little change.

Yes, this is just a demo settings files. For our customers we use the basemaps they want. For example osm.geo2france.fr. By the way, I have to rewrite the settings in order to use environment variables (this is one of your suggestions). I will try to do it this week. I will inject this in the georchestra branch of the project.

**Comment by bchartier** [comment]
PR adaptée et mergée dans develop.

**Pull request closed without merging**
